# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: thisblog
email: tesfaldet@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Forever a student in computer science. A music nerd with a penchant for graphic design; interested in the fields of
  computer vision, machine learning, and computer graphics.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://mtesfaldet.net" # the base hostname & protocol for your site
github_username: tesfaldet
owner: "Matthew Tesfaldet"

# Build settings
markdown: kramdown

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Matthew Tesfaldet"
